### ISSUE TITLE
Review #1 - Algunos componentes no cargan correctamente.

### ISSUE THREAD

**Issue by FacundoEG** [RobledoAkerman/mi-portfolio#1]
Hola Dani! como estas? te dejo un detalle para revisar en el desafío.

Fijate que algunos de los compontentes no estan cargando bien a veces cuando vas cambiando la pagina:

![image](https://user-images.githubusercontent.com/79592789/152060474-10e8e653-5d12-49dd-a1d8-2dab86752127.png)

![image](https://user-images.githubusercontent.com/79592789/152060489-e763b4b5-fd5c-4c13-a572-bb7a34b4b2ba.png)

Te sugiero que para que esto cargue bien, cambies los scripts de "async" a "defer" asi cada js espera que termine de cargar para poder seguir al otro, porque me parece que se estan queriendo cargar todos al mismo tiempo y eso genera errores.

Despues el resto de la pagina te quedo hermosa! me encanto el diseño la verdad

Revisate eso y ya quedaría aprobado el desafío!

**Comment by danielaAkerman** [comment]
Gracias siempre!
